Exercise 5
Systems-Development-and-Frameworks/Felni pull request #11
Opened 2020-12-11 10:24 UTC by NicolasTsc

2021-01-01 18:05 UTC, roschaefer requested changes
![so far so good](https://media.giphy.com/media/2ddA3qDsGi2WE2G3At/giphy.gif)

This is an intermediary feedback, so no grading here. I think it looks good already. The biggest problem that I can see right now is that you run completely different code in your tests vs. during production. See this forum post in our moodle where I tried to explain the different options: https://moodle.htw-berlin.de/mod/forum/discuss.php?d=134501#p198015

You can run tests against Neo4J by cleaning the database for each test case or you could mock the neo4j driver response.

Also, play a little with Cypher. You can DRY up your code a lot. Don't be afraid to find and mutate sub-graphs in your database in one statement.

2021-01-04 17:34 UTC, moengers approved these changes
Sieht sehr gut aus!
Wir haben nichts zu beanstanden.

Zu dem Neo4J Teil können wir euch leider nicht viel sagen, da wir uns mit GraphCMS beschäftigt haben.

2021-01-04 17:34 UTC, moengers commented on backend/README.md
> +## Why we decided to use the Neo4J architecture
⭐ For explaining WHY you have chosen the scenario in the README.md.

2021-01-04 17:34 UTC, moengers commented on backend/README.md
> +## Installation guide for Apollo Backend + Neo4J
⭐ For choosing a scenario and writing installation instructions in README.md.

2021-01-04 17:34 UTC, moengers commented on backend/.env.template
> +JWTSECRET=yourjwtsecret
⭐ For not committing sensitive secrets (e.g. API keys) unencrypted to the repository.

2021-01-04 17:34 UTC, moengers commented on backend/src/index.spec.ts
> +const setupServerAndReturnTestClient = async (testToken?) => {
⭐ ⭐ Your software tests are free of side effects.

2021-01-04 17:34 UTC, moengers commented on backend/src/resolvers.ts
>    Mutation: {
⭐ ⭐ Data created in mutations are persisted and your queries and mutations still work as expected.

2021-01-08 22:07 UTC, moengers approved these changes
Ausversehen auf den Button gekommen, dass eine neue review angefragt wird.
Hier ist nichts weiter sonst.

2021-01-11 09:07 UTC, medizinmensch approved these changes
Hi Felni!

For me it looks like you fixed @roschaefer's biggest concern (running different code in tests vs. production).
I especially liked your README as well as your very clear and nicely readable test cases! 👏 

Thanks also to @moengers for his review!

To conclude:

:star: For choosing a scenario   and writing installation instructions in README.md.
:star:   For explaining WHY you have chosen the scenario in the README.md.
:star: For not committing   sensitive secrets (e.g. API keys) unencrypted to the repository.
:star:   :star: Data created in mutations are persisted and your queries and mutations   still work as expected.
:star: :star: Your software   tests are free of side effects.
:star:   Your database is never left in an invalid state.
:star: You deny the client to   call mutations and queries of your subschema directly.
:star:   For requesting a review and reviewing another team's PR.

That makes a total of 10/10 :star:

![Todo](https://media.giphy.com/media/jO2VAnKyAtgcSWxxVf/giphy.gif)

2021-01-11 15:07 UTC, merged